### PR TITLE
Fixed markdown fonts not being resized properly

### LINKED ISSUE #335: QMarkdownTextEdit changes font, and font size during Bold and Italic operations
A user reported that our Markdown editor (QMarkdownTextEdit) changes font, and font size during Bold and Italic operations.

@pbek Is it due to a recent change?

image

Screen Shot 2022-09-16 at 2 15 52 PM

### PR DESCRIPTION
**Pull request by zjeffer**
Before and after:

https://user-images.githubusercontent.com/4633209/224572526-3f110831-baca-46bd-97cd-093c36f070a3.mp4

Fixes #335

### CODE REVIEW

File: src/noteeditorlogic.h [hunk 1]
```diff
@@ -35,7 +35,7 @@ class NoteEditorLogic : public QObject
 
     static QString getFirstLine(const QString &str);
     static QString getSecondLine(const QString &str);
-    void setTheme(Theme theme, QColor textColor);
+    void setTheme(Theme newTheme, QColor textColor, qreal fontSize);
```
Comment (bjorn) [inline src/noteeditorlogic.h:38]: I'd prefer if we just kept calling this `theme` rather than `newTheme`. For consistency we could rename the occurrences of `newTheme` elsewhere to `theme` instead.

**Review by bjorn — APPROVED** [review]
Looks good, just one small nitpick. :-)

**Comment by nuttyartist** [comment]
Oh, thanks for this, that has been so annoying!
