### PR TITLE
Linux: Restore code for frameless window resizing

### LINKED ISSUE #483: [Regression] [Linux] Window resizing is broken in frameless mode
Window resizing in v1.5.0 (frameless mode):

https://user-images.githubusercontent.com/626206/219870703-41d77515-b652-43bd-a2e4-1997e93eed0f.mp4

<br>

Window resizing in v2.0.0 or `dev` (frameless mode):

https://user-images.githubusercontent.com/626206/219870792-bab25c1f-5d6c-4e2d-8a7c-4f8ca2db5eda.mp4

<br>

As you can see, we can't resize the window in v2.0.0 like we could in v1.5.0.

Because frameless mode is the default experience, we should probably fix this before releasing 2.1.0.

PS: This is unrelated to #454.

### PR DESCRIPTION
**Pull request by guihkx**
Linux users can not easily resize Notes' window if they have 'frameless mode' enabled (which is the default behavior).

This change restores this ability, which was present in v1.5.0, but was later removed in v2.0.0 by commit ddd79edf077158e0e62cc2b432f669e60a7d9bfb.

Fixes #483

---

**Before:**

https://user-images.githubusercontent.com/626206/220225135-ad2ba1c8-092b-4ab9-8646-dbc659a2f3bc.mp4

<br>

**After:**

https://user-images.githubusercontent.com/626206/220225150-ac97a46c-1e80-4b7e-8930-ab6c258ed64f.mp4

### CODE REVIEW

File: src/mainwindow.cpp [hunk 1]
```diff
@@ -2189,8 +2190,8 @@ void MainWindow::maximizeWindow()
 void MainWindow::minimizeWindow()
 {
 #if defined(Q_OS_LINUX) || defined(Q_OS_FREEBSD)
```
Comment (bjorn) [inline src/mainwindow.cpp:2192]: In other places we're now using `#if defined(Q_OS_UNIX) && !defined(Q_OS_MACOS)`, and I think it would be good to change it here too.

File: src/mainwindow.cpp [hunk 2]
```diff
@@ -2166,7 +2167,7 @@ void MainWindow::maximizeWindow()
 
     } else {
         setWindowState(windowState() | Qt::WindowMaximized);
-        //        setMargins(QMargins(0,0,0,0));
+        setMargins(QMargins(0, 0, 0, 0));
```
Comment (bjorn) [inline src/mainwindow.cpp:2170]: I'll just note that `QMargins()` already "Constructs a margins object with all margins set to 0.", so I would suggest to leave out the `0, 0, 0, 0` everywhere.

**Review by bjorn — COMMENTED** [review]
Haven't tested this, just adding two small comments.

Regarding the before / after captures, what happened to the shadow in the after version?

File: src/mainwindow.cpp (hunk 1 above)
Comment (guihkx) [reply src/mainwindow.cpp:2192]: Absolutely! I just deliberately chose not to do that in this PR to avoid making it too overwhelming for reviewers. :p

As soon as this and other PRs I have are accepted (or rejected :p), I'll send a new one updating those as well. :D

File: src/mainwindow.cpp (hunk 2 above)
Comment (guihkx) [reply src/mainwindow.cpp:2170]: Good catch.

**Comment by guihkx** [comment]
> Regarding the before / after captures, what happened to the shadow in the after version?

Good question... I'll try to investigate that once I get home.

**Comment by guihkx** [comment]
Ah, I *think* I got it.

The shadows are still there, they're just less intensive. On a complete white background, they stand out a bit better:

image

And I think that happens because we're making the window background translucent (with [`Qt::WA_TranslucentBackground`](https://doc.qt.io/qt-5/qt.html#:~:text=Qt%3A%3AWA_TranslucentBackground)).

If I don't set the translucent attribute, the shadows are much more intensive (though the window itself looks terrible because of the margins added to resize the window):

image

I couldn't find a way to set the background completely transparent, but in my opinion this does not look too bad. It's certainly better than not being able to resize the window...

**Comment by nuttyartist** [comment]
I tested the latest build and works very well. Solves the problem I mentioned in #489.

**Comment by nuttyartist** [comment]
Oh well. It seems to work only on the top part of the window, not the rest.

**Comment by guihkx** [comment]
> Oh well. It seems to work only on the top part of the window, not the rest.

It doesn't match what I show on my second video, then?

>I'll try to create a video.

Thanks, that will be helpful, I think.

**Comment by nuttyartist** [comment]
> > Oh well. It seems to work only on the top part of the window, not the rest.
> 
> It doesn't match what I show on my second video, then?
> 
> > I'll try to create a video.
> 
> Thanks, that will be helpful, I think.

No... it seems to work only well on the top editor area.

https://user-images.githubusercontent.com/16375940/220425795-d463cfb5-cf04-4718-bd26-5371c6949590.mp4

**Comment by guihkx** [comment]
Uh-oh. That looks unusual to me. 

I'm not sure what if the problem is elementaryOS-specific (works well on Ubuntu 18.04 with Unity though, which is what elementaryOS 5 is based on).

I'll setup a VM to test it out.

**Comment by guihkx** [comment]
I just noticed something on your video that should be fixed (in a subsequent PR).

At around 0:16 seconds, you were able to resize the window there. But that's wrong, because you should never be able to resize the window while the cursor is hovering *inside* the window, only *outside* of it.

Anyway, I could not reproduce your issue on a live CD image of elementaryOS 5:

https://user-images.githubusercontent.com/626206/220441018-23f4ce2f-6a08-4235-b09c-d3fe0582bde1.mp4

<br>

But yeah, the blurry icon issue you mentioned in #489 is real.

**Comment by guihkx** [comment]
I'm thinking you could've had a different version of Notes already running when you tried to open the AppImage from this pull request, because the shadows around the window on your video look different from mine.

**Comment by bjorn** [comment]
> I'm thinking you could've had a different version of Notes already running when you tried to open the AppImage from this pull request, because the shadows around the window on your video look different from mine.

This happens to me all the time as well when I try to test stuff, heh.

> The shadows are still there, they're just less intensive. On a complete white background, they stand out a bit better:

In that case, could it be that we're rendering the shadows in gray rather than black? Because they look like they are lighter than the background in your second screen capture.

**Comment by nuttyartist** [comment]
> I'm thinking you could've had a different version of Notes already running when you tried to open the AppImage from this pull request, because the shadows around the window on your video look different from mine.

Oh, maybe. I'll test again and report back.

> In that case, could it be that we're rendering the shadows in gray rather than black? Because they look like they are lighter than the background in your second screen capture.

They definitely don't look good in that video. I will test now on my end...

**Comment by guihkx** [comment]
>In that case, could it be that we're rendering the shadows in gray rather than black?

It could be, but I'm not really a graphics person and the code in  `gaussianDist()` / `fillRectWithGradient()` scares me a little bit. 😅

Just keep in mind that the shadows have been like that v1.0.0, all I'm doing here is restoring the code so we can resize the window again.

>it's still very inconsistent on my machine

Just keep in mind that the Qt 5 build has some mouse-grabbing issues with `startSystemMove()` (I reported it in #472), so once you release the mouse button, the cursor gets "stuck" until you left click anywhere inside the window again.

I also just fixed the issue where you were able to resize the window while your mouse was inside of it.

Now you should only be able to resize it by its outer edges. Please test again once you can.

>And apparently, it's because Hide to tray icon was on but elementary doesn't show up the icon in the tray area (I think it doesn't support it?) so I kept thinking the app was closed while it was still open until I disabled it.

Ohhh, right. Both GNOME and elementary don't support tray icons natively, so when we close the window, Notes "hides" itself and there's no way of restoring it because we don't have the system tray...

It should be an easy fix, I think: We probably just have to check if there's a working system tray with [`QSystemTrayIcon::isSystemTrayAvailable()`](https://doc.qt.io/qt-5/qsystemtrayicon.html#isSystemTrayAvailable) when the user requests to close the app.

**Comment by nuttyartist** [comment]
> It should be an easy fix, I think: We probably just have to check if there's a working system tray with [QSystemTrayIcon::isSystemTrayAvailable()](https://doc.qt.io/qt-5/qsystemtrayicon.html#isSystemTrayAvailable) when the user requests to close the app.

Nice one.

> Now you should only be able to resize it by its outer edges. Please test again once you can.

Sure I'll test now.

**Comment by nuttyartist** [comment]
> The Qt 5 build has some mouse-grabbing issues with startSystemMove() (I reported it in https://github.com/nuttyartist/notes/issues/472), so once you release the mouse button, the cursor gets "stuck" until you left click anywhere inside the window again.

That's annoying. With Qt6 build it doesn't happen?

Anyway, tt seems to work like 2.0.0 (but better because the width of the panes doesn't change now on each resize).

So I approve this PR.

**Comment by guihkx** [comment]
>That's annoying. With Qt6 build it doesn't happen?

That's correct, it's a Qt5-only issue on Linux (I think it's also specific to X11).

Anyway, I just rebased against `dev` so I can merge this branch manually (merging with GitHub's own tool removes my commit signature).

Thanks for testing, y'all!
