### PR TITLE
Fix memory leak, prevent corrupt database, fix typos in qml, various other fixes

### LINKED ISSUE #234: Note don't get saved
Notes won't get saved if they have content like this:
```
"hello %1 hello"
```

### LINKED ISSUE #727: Qt 6.8 build warning from CMake
On 39fc4ecf90a32ea20dbe3ed8b421e61e9fa37b8b, with Qt 6.8.0, on Linux:

```
CMake Warning (dev) at /usr/lib/cmake/Qt6Qml/Qt6QmlMacros.cmake:2958 (message):
  src/qml/Utilities.js is not an ECMAScript module and also doesn't contain
  '.pragma library'.  It will be re-evaluated in the context of every QML
  document that explicitly or implicitly imports io.github.nuttyartist.notes.
  Set its QT_QML_SKIP_QMLDIR_ENTRY source file property to FALSE if you
  really want this to happen.  Set it to TRUE to prevent it.
Call Stack (most recent call first):
  /usr/lib/cmake/Qt6Qml/Qt6QmlMacros.cmake:891 (qt6_target_qml_sources)
  /usr/lib/cmake/Qt6Qml/Qt6QmlMacros.cmake:1148 (qt6_add_qml_module)
  CMakeLists.txt:328 (qt_add_qml_module)
This warning is for project developers.  Use -Wno-dev to suppress it.
```

Full log:

```
$ cmake -B build -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Release
-- The CXX compiler identification is GNU 14.2.1
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/sbin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Trying to find Qt 6...
-- Performing Test HAVE_STDATOMIC
-- Performing Test HAVE_STDATOMIC - Success
-- Found WrapAtomic: TRUE
-- Found OpenGL: /usr/lib/libOpenGL.so
-- Found WrapOpenGL: TRUE
-- Found XKB: /usr/lib/libxkbcommon.so (found suitable version "1.7.0", minimum required is "0.5.0")
-- Found WrapVulkanHeaders: /usr/include
-- Success! Configuration details:
-- App name: Notes
-- App version: 2.3.1
-- Qt version: 6.8.0
-- Update checker: ON
-- Pro Version: ON
-- Build type: Release
CMake Warning (dev) at /usr/lib/cmake/Qt6Qml/Qt6QmlMacros.cmake:2958 (message):
  src/qml/Utilities.js is not an ECMAScript module and also doesn't contain
  '.pragma library'.  It will be re-evaluated in the context of every QML
  document that explicitly or implicitly imports io.github.nuttyartist.notes.
  Set its QT_QML_SKIP_QMLDIR_ENTRY source file property to FALSE if you
  really want this to happen.  Set it to TRUE to prevent it.
Call Stack (most recent call first):
  /usr/lib/cmake/Qt6Qml/Qt6QmlMacros.cmake:891 (qt6_target_qml_sources)
  /usr/lib/cmake/Qt6Qml/Qt6QmlMacros.cmake:1148 (qt6_add_qml_module)
  CMakeLists.txt:328 (qt_add_qml_module)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Found X11: /usr/include
-- Looking for XOpenDisplay in /usr/lib/libX11.so;/usr/lib/libXext.so
-- Looking for XOpenDisplay in /usr/lib/libX11.so;/usr/lib/libXext.so - found
-- Looking for gethostbyname
-- Looking for gethostbyname - found
-- Looking for connect
-- Looking for connect - found
-- Looking for remove
-- Looking for remove - found
-- Looking for shmat
-- Looking for shmat - found
-- Looking for IceConnectionNumber in ICE
-- Looking for IceConnectionNumber in ICE - found
-- Configuring done (10.4s)
-- Generating done (0.1s)
-- Build files have been written to: /home/gui/dev/notes/build
```

### LINKED ISSUE #730: Crash when exiting
Note: this might reference #715.

I've built Notes from source a few minutes ago to give it a run and stumbled upon both a bug and a crash that might be related to it. When I open the settings they are not rendered properly as can be seen below. Furthermore, the window cannot be moved since it closes immediately when clicking anywhere but in content area. Clicking in the area where my mouse is apparently counts as 'in content area' since the window does not close.
image

So much on the bug.

The crash occours every time when closing the application after the settings window has been used (this might relate to #715). 
I have no experience with gdb, all I can provide for now is
```
Thread 1 "notes" received signal SIGSEGV, Segmentation fault.
0x00007ffff5746804 in QWindow::parent(QWindow::AncestorMode) const ()
    from /lib64/libQt6Gui.so.6
```

Build output (stripped):
```
$ cmake .. -DCMAKE_BUILD_TYPE=Debug
-- The CXX compiler identification is GNU 14.2.1
-- Performing Test HAVE_STDATOMIC - Success
-- Found WrapAtomic: TRUE
-- Found OpenGL: /usr/lib64/libOpenGL.so
-- Found WrapOpenGL: TRUE
-- Found XKB: /usr/lib64/libxkbcommon.so (found suitable version "1.7.0", minimum required is "0.5.0")
-- Found WrapVulkanHeaders: /usr/include
-- Success! Configuration details:
-- App name: Notes
-- App version: 2.3.1
-- Qt version: 6.8.1
-- Update checker: ON
-- Pro Version: ON
-- Build type: Debug
CMake Warning (dev) at /usr/lib64/cmake/Qt6Qml/Qt6QmlMacros.cmake:3051 (message):
  src/qml/Utilities.js is not an ECMAScript module and also doesn't contain
  '.pragma library'.  It will be re-evaluated in the context of every QML
  document that explicitly or implicitly imports io.github.nuttyartist.notes.
  Set its QT_QML_SKIP_QMLDIR_ENTRY source file property to FALSE if you
  really want this to happen.  Set it to TRUE to prevent it.
Call Stack (most recent call first):
  /usr/lib64/cmake/Qt6Qml/Qt6QmlMacros.cmake:896 (qt6_target_qml_sources)
  /usr/lib64/cmake/Qt6Qml/Qt6QmlMacros.cmake:1232 (qt6_add_qml_module)
  CMakeLists.txt:328 (qt_add_qml_module)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Found X11: /usr/include
-- Looking for XOpenDisplay in /usr/lib64/libX11.so;/usr/lib64/libXext.so
-- Looking for XOpenDisplay in /usr/lib64/libX11.so;/usr/lib64/libXext.so - found
-- Looking for gethostbyname - found
-- Looking for connect - found
-- Looking for remove - found
-- Looking for shmat - found
```

Make yields the following warning (stripped absolute path to notes folder):
```
notes/src/mainwindow.cpp: In member function ‘virtual bool MainWindow::eventFilter(QObject*, QEvent*)’:
notes/src/mainwindow.cpp:3921:42: warning: ‘static void QApplication::setActiveWindow(QWidget*)’ is deprecated: Use QWidget::activateWindow() instead. [-Wdeprecated-declarations]
 3921 |             QApplication::setActiveWindow(
      |             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
 3922 |                     this); // TODO: The docs say this function is deprecated but it's the only one
      |                     ~~~~~                 
In file included from /usr/include/qt6/QtWidgets/QApplication:1,
                 from notes/build/Notes_autogen/include/ui_mainwindow.h:13,
                 from notes/src/mainwindow.cpp:8:
/usr/include/qt6/QtWidgets/qapplication.h:84:17: note: declared here
   84 |     static void setActiveWindow(QWidget* act);
      |    
```

I run Fedora 41 with GNOME DE (which should provide wayland? cmake found x11 however).

### PR DESCRIPTION
**Pull request by zjeffer**
I added an option to CMakeLists.txt to enable address sanitizer (first commit). I ran it and noticed the following memory leak when closing the main window:

```
=================================================================
==143229==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 24 byte(s) in 1 object(s) allocated from:
    #0 0x56a6832241b2 in operator new(unsigned long) (/home/zjeffer/git/notes/build/notes+0x2521b2) (BuildId: f3febbdce0342b087d8f64ae39d11f58ce6cd95c)
    #1 0x56a6833aadfb in MainWindow::MainWindow(QWidget*) /home/zjeffer/git/notes/src/mainwindow.cpp:132:20
    #2 0x56a6833a8184 in main /home/zjeffer/git/notes/src/main.cpp:96:16
    #3 0x7a8a82a34e07 in __libc_start_call_main /usr/src/debug/glibc/glibc/csu/../sysdeps/nptl/libc_start_call_main.h:58:16
    #4 0x7a8a82a34ecb in __libc_start_main /usr/src/debug/glibc/glibc/csu/../csu/libc-start.c:360:3
    #5 0x56a6830e5584 in _start (/home/zjeffer/git/notes/build/notes+0x113584) (BuildId: f3febbdce0342b087d8f64ae39d11f58ce6cd95c)

SUMMARY: AddressSanitizer: 24 byte(s) leaked in 1 allocation(s).
```
It's not much but it should be fixed either way, so I did that in the 3rd commit. We have lots more (and much bigger) memory leaks btw, will take a look at the others too.

* In the 2nd commit, I fixed a deprecation warning (setActiveWindow)
* In the 4th commit, I just fixed some typos in qml files.
* In the 5th commit, I fixed an issue where the folder structure can get corrupted in the database when moving a note into the same folder it's already in,  by simply returning early. I followed @guihkx [steps](https://github.com/nuttyartist/notes/issues/504#issuecomment-1595822308) with a non-empty note and could not reproduce the issue after this commit. It is still reproducable when moving an *empty* note into a folder.
* In the 6th commit, I fixed clang-formatting of the emit keyword
* In the 7th commit, I fixed some possible injection with .arg() chains
* In the 8th commit, I fixed a cmake warning
* In the 9th commit, I fixed a crash on exit (#730)

Closes #234
Closes #730 
Closes #727

### CODE REVIEW

**Comment by zjeffer** [comment]
There's an issue with clang-format, apparently it wants to format 
```
emit itemDelegate()->sizeHintChanged(index);
```
into
```
emit itemDelegate() -> sizeHintChanged(index);
```
Investigating :thinking:

**Comment by zjeffer** [comment]
@guihkx Done, it worked!

There's a problem with the snap build, seems like an authentication issue. @nuttyartist can you take a look?

**Comment by guihkx** [comment]
>Done, it worked!

Nice.

>There's a problem with the snap build, seems like an authentication issue

Hmm, I actually think that error comes from `sg`, not `snapcraft`...

Do you wanna try to also use `ubuntu-22.04` for the snap job?

It looks like the recent upgrade of `ubuntu-latest` to Ubuntu 24.04 will require a few changes on our side, but we don't have to do it right now, because the `ubuntu-22.04` runner will not be deprecated anytime soon.

**Comment by nuttyartist** [comment]
Thanks, @zjeffer! I want to take some time to review this, hopefully today.

File: src/treeviewlogic.cpp
Comment (guihkx) [inline src/treeviewlogic.cpp:1]: The changes to this file are fine, I guess, but I can still reproduce the database corruption of #504 by following [these reproduction steps](https://github.com/nuttyartist/notes/issues/504#issuecomment-1595822308).

File: src/mainwindow.cpp [hunk 1]
```diff
@@ -3918,10 +3920,7 @@ bool MainWindow::eventFilter(QObject *object, QEvent *event)
     }
     case QEvent::ActivationChange: {
         if (m_editorSettingsWidget->isHidden()) {
-            QApplication::setActiveWindow(
-                    this); // TODO: The docs say this function is deprecated but it's the only one
-                           // that works in returning the user input from m_editorSettingsWidget
-                           // Qt::Popup
+            QWidget::activateWindow();
```
Comment (guihkx) [inline src/mainwindow.cpp:3923]: Nit: Please put this into a separate commit.

File: CMakeLists.txt [hunk 2]
```diff
@@ -32,6 +33,15 @@ set(CMAKE_AUTOMOC ON)
 set(CMAKE_AUTOUIC ON)
 set(CMAKE_AUTORCC ON)
 
+# address sanitizer can be enabled by running cmake with -DENABLE_ASAN=ON
+if(ENABLE_ASAN AND (CMAKE_CXX_COMPILER_ID STREQUAL "GNU"
+                    OR CMAKE_CXX_COMPILER_ID MATCHES "Clang"))
+  message(STATUS "Enabling AddressSanitizer")
+  set(ADDRESS_SANITIZER_FLAGS "-fsanitize=address -fno-omit-frame-pointer")
+  set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${ADDRESS_SANITIZER_FLAGS}")
+  set(CMAKE_LINKER_FLAGS "${CMAKE_LINKER_FLAGS} ${ADDRESS_SANITIZER_FLAGS}")
```
[the remark this answers is not in the document]
Comment (zjeffer) [reply CMakeLists.txt]: Likely a copilot hallucination, nicely spotted :)

File: .github/workflows/linux.yml [hunk 3]
```diff
@@ -266,7 +266,7 @@ jobs:
 
   snap:
     name: snap
-    runs-on: ubuntu-latest
+    runs-on: ubuntu-22.04 # older version to fix sg authentication issues
```
[the remark this answers is not in the document]
Comment (zjeffer) [reply .github/workflows/linux.yml]: done

File: src/mainwindow.cpp (hunk 1 above)
Comment (zjeffer) [reply src/mainwindow.cpp:3923]: done

Comment (guihkx) [reply src/mainwindow.cpp:3923]: I'm not sure why you can't reproduce it, but here's a video if it helps:

https://github.com/user-attachments/assets/418ffeae-e4a6-4857-b3f1-81e3da589992

P.S.: I completely removed `~/.config/Awesomeness` prior to recording.

I also didn't do all steps because my terminal was already being spammed with `qt.sql.qsqlquery: QSqlQuery::value: not positioned on a valid record` at only step 2, and by then the db is already broken.

File: src/treeviewlogic.cpp
Comment (guihkx) [reply src/treeviewlogic.cpp:1]: >Did you test it on a clean database?

Yup. I'm not sure why you can't reproduce it, but here's a video if it helps:

https://github.com/user-attachments/assets/418ffeae-e4a6-4857-b3f1-81e3da589992

I also didn't do all steps because my terminal was already being spammed with `qt.sql.qsqlquery: QSqlQuery::value: not positioned on a valid record` at only step 2, and by then the db is already broken.

Comment (zjeffer) [reply src/treeviewlogic.cpp:1]: Ah, we're seeing 2 different bugs. The bug I fixed in this PR occured when moving a non-empty node into the folder it's already in. The bug you're triggering in your video happens when moving an _empty_ note into a folder. It does indeed also trigger the same problem where folders then can't be deleted.

**Review by guihkx — APPROVED** [review]

**Comment by nuttyartist** [comment]
@zjeffer Thanks a lot for this! We should probably drop the mention of fixing https://github.com/nuttyartist/notes/issues/504 since this bug is still reproducible.

**Review by nuttyartist — APPROVED** [review]

**Comment by nuttyartist** [comment]
@zjeffer, in order to fix https://github.com/nuttyartist/notes/issues/730, can you please add `this` as a parent to all instances of `QWidget::createWindowContainer` in the code?
